CREATE TABLE USUARIO(
    ID_USUARIO INT AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    CEP VARCHAR(8),
    PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE FARMACIA(
    ID_FARMACIA INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CEP VARCHAR(8),
    LATITUDE DECIMAL(10,7),
    LONGITUDE DECIMAL(10,7),
    HORARIO_ABERTURA TIME,
    HORARIO_FECHAMENTO TIME,
    DELIVERY BOOLEAN,
    PRIMARY KEY(ID_FARMACIA)
);

CREATE TABLE MEDICAMENTO(
    ID_MEDICAMENTO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    PRINCIPIO_ATIVO VARCHAR(150) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    DOSAGEM VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_MEDICAMENTO)
);

CREATE TABLE MEDICAMENTO_FARMACIA(
    ID_MEDICAMENTO_FARMACIA INT AUTO_INCREMENT,
    ID_MEDICAMENTO INT NOT NULL,
    ID_FARMACIA INT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ID_MEDICAMENTO FOREIGN KEY(ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO),
    CONSTRAINT FK_ID_FARMACIA FOREIGN KEY(ID_FARMACIA) REFERENCES FARMACIA(ID_FARMACIA),
    CONSTRAINT UQ_MEDICAMENTO_FARMACIA UNIQUE(ID_MEDICAMENTO, ID_FARMACIA),
    PRIMARY KEY(ID_MEDICAMENTO_FARMACIA)
);

CREATE TABLE HISTORICO_PRECO(
    ID_HISTORICO_PRECO INT AUTO_INCREMENT,
    ID_MEDICAMENTO_FARMACIA INT NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    CONSTRAINT FK_ID_MEDICAMENTO_FARMACIA FOREIGN KEY(ID_MEDICAMENTO_FARMACIA) REFERENCES MEDICAMENTO_FARMACIA(ID_MEDICAMENTO_FARMACIA),
    PRIMARY KEY(ID_HISTORICO_PRECO)
);